#version: '3'
#services:
#  conversations-batch-api:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    image: conversations-batch-api_com_mysql/api
#    ports:
#      - '8080:8080'
#      - '5005:5005'
#    environment:
#      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
#      - PROFILE=dev
#    links:
#      - db
#  db:
#    image: mysql:5.7
#    ports:
#      - '3306:3306'
#    environment:
#      - MYSQL_ROOT_HOST=%
#      - MYSQL_DATABASE=app
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=biv@user
#    volumes:
#      - ./docker/volume_mysql:/var/lib/mysql